package v1.application;

import v1.entities.Expense;
import v1.entities.ExpenseManager;
import v1.enums.Category;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Scanner;

public class Program {
    public static void main(String[] args) {

        // Use dot as decimal separator (e.g. 35.00) regardless of system language
        Locale.setDefault(Locale.US);

        Scanner sc = new Scanner(System.in);
        ExpenseManager expm = new ExpenseManager();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        int select = 0;

        // Ids are generated by the program, starting at 1
        Long id = 1L;

        System.out.println("--Welcome to your Expense Tracker--");

        do {
            System.out.println();
            System.out.println("1 - Add expense");
            System.out.println("2 - Remove expense");
            System.out.println("3 - List all expenses");
            System.out.println("4 - Filter by month");
            System.out.println("5 - Show total");
            System.out.println("0 - Exit");
            System.out.print("Choose an option: ");

            select = sc.nextInt();

            switch (select) {
                case 0:
                    System.out.println("Goodbye!");
                    break;
                case 1:
                    System.out.print("Description: ");
                    // Consume the line break left by nextInt()
                    sc.nextLine();
                    String description = sc.nextLine();
                    System.out.print("Amount: ");
                    BigDecimal amount = sc.nextBigDecimal();
                    System.out.print("Date (dd/MM/yyyy): ");
                    LocalDate date = LocalDate.parse(sc.next(), fmt);
                    System.out.print("Category (FOOD, TRANSPORT, HOUSING, LEISURE, HEALTH, OTHER): ");
                    // Converts the typed text into the matching Category value
                    Category category = Category.valueOf(sc.next());

                    Expense expense = new Expense(id, description, amount, date, category);
                    expm.add(expense);

                    System.out.printf("Expense added! (id %d)%n", id);
                    id++;
                    break;
                case 2:
                    System.out.print("Enter the expense id: ");
                    Long removeId = sc.nextLong();
                    expm.remove(removeId);
                    System.out.println("Expense removed!");
                    break;
                case 3:
                    if (expm.listAll().isEmpty()) {
                        System.out.println("No expenses registered.");
                    } else {
                        for (Expense e : expm.listAll()) {
                            System.out.println(e);
                        }
                    }
                    break;
                case 4:
                    System.out.print("Month: ");
                    int month = sc.nextInt();
                    System.out.print("Year: ");
                    int year = sc.nextInt();

                    if (expm.filterByMonth(month, year).isEmpty()) {
                        System.out.println("No expenses found for this month.");
                    } else {
                        for (Expense e : expm.filterByMonth(month, year)) {
                            System.out.println(e);
                        }
                    }
                    break;
                case 5:
                    System.out.println("Total: " + expm.calculateTotal());
                    break;
                default:
                    System.out.println("(Enter a valid number between 0 and 5)");
            }

        } while (select != 0);

        sc.close();
    }
}